[workspace]
members = ["crates/parser", "crates/cli"]
resolver = "3"

[workspace.dependencies]
base64 = "0.22.1"
miniz_oxide = "0.8.9"
once_cell = "1.21.3"
quick-xml = "0.38.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
clap = "4.5.53"
zstd = "0.13.3"
