[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true, features = ["derive"] }
octo = { path = "../parser" }
regex = { workspace = true }

[[bin]]
name = "octo"
path = "src/main.rs"
